import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { BsFillMoonStarsFill } from "react-icons/bs";

export const metadata: Metadata = {
  title: "Portfolio by Lance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" min-h-screen bg-white px-10">
        <nav className=" py-10 mb-12 flex justify-between">
          <h1 className=" text-xl  font-burtons">developedbylance</h1>
          <ul className=" flex items-center">
            <li>
              <BsFillMoonStarsFill className=" cursor-pointer text-2xl" />
            </li>
            <li>
              <Link
                className=" bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                href="#"
              >
                Resume
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
